### ISSUE TITLE
dd_robot2.urdf

### ISSUE THREAD

**Issue by Lauro199471** [PacktPublishing/ROS-Robotics-By-Example#1]
for the dd_robot2.urdf I am getting this. It doesnt look like the book dd_robot2.urdf 
![robot](https://user-images.githubusercontent.com/13907836/35762983-0754da6c-0857-11e8-9f91-572bbd1ca1d9.png)

**Comment by Lauro199471** [comment]
The book looks like this: 
![screenshot from 2018-02-02 20-25-48](https://user-images.githubusercontent.com/13907836/35762997-46e5c0e2-0857-11e8-8032-1d701330ad13.png)

**Comment by YCD1234** [comment]
me too .... how did you solve it?

**Comment by Lauro199471** [comment]
Its been a year i really forgot lol but i did solve it. I dont use ROS as much anymore :( I think i have the solution in my github

**Comment by Lauro199471** [comment]
https://answers.ros.org/question/281689/dd_robot2urdf-help/
