### ISSUE TITLE
error running xacro file

### ISSUE THREAD

**Issue by amoghatsunil** [PacktPublishing/ROS-Robotics-By-Example#3]
I am getting this error when i am running the xacro file rrbot3.xacro in chapter 5

![Screenshot from 2021-06-01 07-20-33](https://user-images.githubusercontent.com/61882073/120255570-e6a88f00-c2a9-11eb-9882-17efcdbb2b66.png)

**Comment by tlharmanphd** [comment]
Greetings:
We have analyzed the error in running rrbot3.xacro file. Our code was tested and runs on the Kinetic distribution of ROS.  Since your distribution is Melodic according to the error shown in the url, we have not tested the code for that ROS distribution.
 
 
T.L Harman and Carol Fairchild
